project:
  type: website
  output-dir: docs

website:
  title: "Home"
  site-url: "hogent-cads.github.io/blog/"
  favicon: favicon.ico
  description: "CADS Data Blog"
  navbar:
    logo: logo_cads_white.png
    right:
      - about.qmd
      - icon: globe
        href: https://www.hogent.be/onderzoekscentra/cads
      - icon: github
        href: https://github.com/hogent-cads/
      - icon: linkedin
        href: https://www.linkedin.com/showcase/centre-for-applied-data-science/about/
format:
  html:
    theme: minty
    css: styles.css
    csl: styles/apa.csl   # optioneel voor APA-stijl

bibliography: references/references.bib
reference-section-title: "Referenties"



